config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'
  resources :categories
  resources :products
  devise_for :users, controllers: {sessions: "sessions"}
  resources :users, only: [], shallow: true do
    resources :commerces
  end

  root 'pages#home'

  get '/my_products' => 'products#my_products', as: 'my_products'
  get '/searcher' => 'pages#searcher', as: 'searcher'
  get '/filter' => 'pages#filter', as: 'filter'
  get '/category_filter' => 'pages#category', as: 'category_filter'

  # Cart routes
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  # LineItems routes
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/views/partials/_footer.html.erb
<footer>
  <section class="footer-contact">
    <ul>
      <span>¡Tecnología al alcance de un CLIC!</span>
      <li>
        <i class="fa-brands fa-whatsapp"></i>
        <span>+52-312-777-6969</span>
      </li>
      <li>
        <i class="fa-solid fa-envelope"></i>
        <span>techclic@gmail.com</span>
      </li>
    </ul>
  </section>
  <section class="footer-info">
    <ul>
      <li><a href="/">Sobre nosotros</a></li>
      <li><a href="/">¿Qué hacemos?</a></li>
      <li><a href="/">Preguntas frecuentes</a></li>
      <li><a href="/">Contactanos</a></li>
    </ul>
  </section>
  <section class="footer-social">
    <div class="footer-social-icon">
      <i class="fa-brands fa-facebook"></i>
      <i class="fa-brands fa-instagram"></i>
      <i class="fa-brands fa-twitter"></i>
    </div>
    <span>Copyright 2022 TechClic. All rights reserverd</span>
  </section>
</footer>

app/views/partials/_navbar.html.erb
<nav class='principal-nav'>
  <section class="nav-searcher">
    <a href="/" class="logo">TechClic</a>
    <%= form_tag(searcher_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Buscar...', value: '' %>
      <%= button_tag(type: 'submit', class: 'searcher-submit') do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
    <%= link_to cart_path(@current_cart), class: 'cart-link' do %>
      <i class="fa-solid fa-cart-shopping"></i>
      <div class="new-item <%= 'inactive' if @current_cart.products.size == 0 %>">
      <span> <%= @current_cart.total_products if @current_cart.products.size > 0 %> </span>
      </div>
    <% end %>
  </section>

  <section class="nav-filter">
    <ul class="nav-filter-left">
      <li><a href="/">Promociones</a></li>
      <li><a href="/">Nuevos Articulos</a></li>
      <li><a href="/">Hardware</a></li>
      <li><a href="/">Equipos Armados</a></li>
    </ul>
    <div class="nav-filter-right" data-controller="hello">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <span>Admin</span>
        <% elsif current_user.seller? %>
          <span>Vendedor</span>
        <% else %>
          <span>Comprador</span>
        <% end %>
      <% else %>
        <span>Invitado</span>
      <% end %>
      <div class="menu-icon" id="menu-icon" data-action="hello#menuInteraction">
        <i class="fa-solid fa-caret-down"></i>
      </div>
      <%= render "partials/options_menu" %>
    </div>
  </section>
</nav>

app/views/partials/_options_menu.html.erb
<div class="options-menu inactive menu" id="menu">
  <% if !user_signed_in? %>
    <div>
      <%= link_to 'Iniciar Sesión', new_user_session_path %>
      <%= link_to 'Registrarse', new_user_registration_path %>
    </div>
  <% else %>
    <div>
    <%= link_to "Mis datos", edit_user_registration_path %>
    <%= link_to "Cerrar sesión", destroy_user_session_path, data: { turbo_method: :delete } %>
    </div>
    <% if current_user.seller? %>
      <div class="user-options">
        <%= link_to "Registrar producto", new_product_path %>
        <%= link_to "Mis productos", my_products_path %>
        <% if current_user.commerces.size < 1 || !current_user.commerces.first.persisted?%>
          <%= link_to "Registrar comercio", new_user_commerce_url(current_user) %>
        <% else %>
          <%= link_to "Ver comercio", commerce_url(current_user.commerces.first) %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<script>
  function menuInteraction() {
    const menuIcon = document.getElementById('menu-icon')
    const menu = document.getElementById('menu')

    menuIcon.addEventListener('click', ()=> {
      menu.classList.contains('inactive') ? menu.classList.remove('inactive') : menu.classList.add('inactive')
    })
  }

  menuInteraction();

  function hideMenus(event) {
    const validation = (event.target.matches('.menu') || event.target.matches('.menu-icon') || event.target.matches('.fa-caret-down'));

    if (!validation) {
      menu.classList.add('inactive')
    } 
  }

  document.onclick = hideMenus;
</script>