config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'
  resources :categories
  resources :products
  devise_for :users, controllers: {sessions: "sessions"}
  resources :users, only: [], shallow: true do
    resources :commerces
  end

  root 'pages#home'

  get '/my_products' => 'products#my_products', as: 'my_products'
  get '/searcher' => 'pages#searcher', as: 'searcher'
  get '/filter' => 'pages#filter', as: 'filter'
  get '/category_filter' => 'pages#category', as: 'category_filter'

  # Cart routes
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  # LineItems routes
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end

  def total_products
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.quantity
    end
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h2>Tu carrito</h2>

<table class="cart-table">
  <tr>
    <th>Producto</th>
    <th>Precio</th>
    <th>Cantidad</th>
    <th>Total</th>
  </tr>
  <% @cart.line_items.each do |line_item| %>
    <tr>
      <td class="td-product">
        <figure>
          <%= image_tag line_item.product.photos[0].variant(resize_to_limit: [500, 500]) %>
        </figure>
        <p><%= line_item.product.name %></p>
      </td>
      <td class="td-price">
        <p> <%= number_to_currency(line_item.product.price, locale: :en) %> </p>
      </td>
      <td class="td-quantity">
        <div>
          <%= link_to "-", line_item_reduce_path(:id => line_item), class: 'remove-cart', data: { turbo_method: :post } %>
          <span> <%= line_item.quantity %> </span>
          <%= link_to "+", line_item_add_path(:id => line_item), class: 'add-cart', data: { turbo_method: :post } %>
        </div>
      </td>
      <td class="td-total">
        <div>
          <p> <%= number_to_currency(line_item.total_price, locale: :en) %> </p>
          <%= button_to "x", line_item_path(line_item), method: :delete %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<div class="footer-cart">
  <h2>Total: <%= number_to_currency(@cart.sub_total, locale: :en) %></h2>
  <%= link_to "Vaciar carrito", cart_path(@current_cart), data: { turbo_method: :delete, confirm: "Are you sure?"} %>
</div>