config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'carts/show'
  resources :categories
  resources :products
  devise_for :users, controllers: {sessions: "sessions"}
  resources :users, only: [], shallow: true do
    resources :commerces
  end

  root 'pages#home'

  get '/my_products' => 'products#my_products', as: 'my_products'
  get '/searcher' => 'pages#searcher', as: 'searcher'
  get '/filter' => 'pages#filter', as: 'filter'
  get '/category_filter' => 'pages#category', as: 'category_filter'

  # Cart routes
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  # LineItems routes
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many_attached :photos
  has_many :line_items, dependent: :destroy

  validates :name, :description, :price, :discount, :brand, :quantity, presence: true;
  validates :price, numericality: { message: "El precio debe tener un valor numerico" }
  validates :discount, numericality: { only_integer: true, message: "Debes ingresar un numero entero" }
  validates :quantity, numericality: { grater_than: 0, message: "Debes haber stock del producto para poder registrarlo" }
  validate :validate_photos

  scope :filter_by_price_lower, -> { order :price }
  scope :filter_by_price_higher, -> { order price: :desc }
  scope :filter_by_score, -> { order score: :desc }
  scope :filter_by_date, -> { order created_at: :desc }

  def self.search(search)
    if search !=""
      product = self.where('(name ILIKE ? OR description ILIKE ? OR model ILIKE ? OR brand ILIKE ?)AND quantity > 0', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else 
      self.order(:id).all.where('quantity > 0')
    end
  end

  def self.search_filter(filtering_param)
    results = self.where(nil)
    results = results.public_send("filter_by_#{filtering_param}")
    results
  end

  private
  def validate_photos
    if photos.size > 0
      photos.each do |photo| 
        unless photo.content_type =~ /^image\/(jpeg|pjpeg|gif|png|bmp)$/ 
          errors.add(:dni_photo, "Una de las imagenes tiene un formato invalido") 
        end
      end
    else
      errors.add(:photos, "Debe subir al menos una foto del producto") 
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend
  before_action :set_product, only: %i[ edit update destroy ]
  before_action :authenticate_user!, except: %i[ show ]
  load_and_authorize_resource

  Pagy::DEFAULT[:items] = 12

  # GET /products or /products.json
  def index
    @pagy, @products = pagy(Product.all)
  end

  def my_products
    @pagy, @products = pagy(current_user.products)
  end
  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.new
  end

  # GET /products/1/edit
  def edit
    delete_attachment(params[:photo_id]) if params.key?(:photo_id)
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "El producto se registro exitosamente" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "El producto se actualizo exitosamente" }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "El producto fue eliminado exitosamente" }
      format.json { head :no_content }
    end
  end

  def delete_attachment(photo_id)
    attachment = ActiveStorage::Attachment.find(photo_id)
    attachment.purge
    redirect_to edit_product_url(@product)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :discount, :user_id, :brand, :quantity, :model, :category_id, photos: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div class="invalid-form alert alert-danger alert-dismissible fade show" role="alert" >
      <strong><span>Ha ocurrido un error:</span></strong><br>
      <aside>
        <% product.errors.each do |error| %>
          <span><%= error.message %></span><br>
        <% end %>
      </aside>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nombre de la publicación' %>
    <%= form.text_field :name, placeholder: 'Ingresa el nombre del producto', required: true %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descripción del producto' %>
    <%= form.text_area :description, placeholder: 'Ingresa un descripción del producto', required: true %>
  </div>

  <div class="field">
    <%= form.label :brand, 'Marca del producto' %>
    <%= form.text_field :brand, placeholder: 'Ingresa la marca del producto', required: true %>
  </div>

  <div class="field">
    <%= form.label :model, 'Modelo del producto' %>
    <%= form.text_field :model, placeholder: 'Ingresa el modelo del producto (si aplica)' %>
  </div>

  <div class="field">
    <%= form.label :price, 'Precio del producto' %>
    <%= form.text_field :price, placeholder: 'Ingresa el precio del producto', required: true %>
  </div>

  <div class="field select-field">
     <%= form.label :category_id, 'Seleccione una categoria para el producto' %>
     <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>

  <div class="field">
    <%= form.label :quantity, 'Disponibilidad del producto' %>
    <%= form.number_field :quantity, placeholder: 'Ingresa stock actual del producto', required: true %>
  </div>

  <div class="field">
    <%= form.label :discount, 'Descuento activo'%>
    <%= form.number_field :discount, value: '0', required: true %>
  </div>

  <span><strong>Subir fotos:</strong></span>
  <div class="file-field">
    <%= form.label :photos do %>
      <% if action_name == 'new' %>
        <%= form.file_field :photos, multiple: true, data: { action:"change->hello#loadFiles" }, class: 'input-file' %>
      <% else %>
        <%= form.file_field :photos, multiple: true, data: { action:"change->hello#loadFiles" }, class: 'input-file' %>
      <% end %>
      <div class="upload photos-field" id="upload">
        <span id="add">+</span>
      </div>
      <div class="photos-bg">
      </div>
    <% end %>
  </div>

  <% if action_name == 'edit' %>
    <span><strong>Fotos actuales:</strong></span>
    <div class="field photos-field photos-delete">
      <% product.photos.each do |photo| %>
        <%= link_to edit_product_path(product, photo_id: photo), class: 'photo' do %>
          <%= image_tag(photo) %>
          <div class="trash-icon">
            <i class="fa-solid fa-trash-can"></i>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit 'Guardar' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="product">
  <header>
    <h1><%= product.name %></h1>
  </header>
  <main class="product-info">

    <section class="product-left-section">

      <div class="product-images">
        <figure class="product-image-main">
          <% if product.photos[0] %>
            <%= image_tag product.photos[0].variant(resize_to_limit: [500, 500]), class: "img-main active" %>
          <% end %>
        </figure>
        <aside class="product-images-list">
          <% product.photos.each do |photo| %>
            <figure class="photo-secundary">
              <%= image_tag photo %>
            </figure>
          <% end %>
        </aside>
      </div>

      <div class="product-seller-info">

        <div class="product-seller">
          <i class="fa-regular fa-circle-user"></i>
          <span> <%= product.user.name %> </span>
        </div>

        <div class="product-score">
          <i class="fa-solid fa-star"></i>
          <span>3.5</span>
          <span>(4 opiniones)</span>
        </div>

      </div>
    </section>

    <section class="product-right-section">

      <div class="product-description">

        <div class="product-features">
          <h3>Descripción</h3>
          <p> <%= product.description %> </p>
          <p><strong>Marca: </strong> <%= product.brand %> </p>
          <% if product.model %>
            <p> <strong>Modelo: </strong><%= product.model %> </p>
          <% end %>
        </div>

        <div class="product-price">
          <h3> $<%= product.price %>MXN</h3>
          <p>Compra a MSI disponible</p>
          <p>Costo de envio: $0.0</p>
          <p><%= product.quantity %> disponibles</p>
          <%= form_with url: "/line_items", method: :post do |form| %>
            <%= form.select :quantity, (1..product.quantity) %>
            <%= form.hidden_field :product_id, value: product.id %>
            <div class="btn-container">
            </div>
            <%= form.submit "Agregar al carrito", class: 'btn-add-cart' %>
          <% end %>
          <div class="btn-container">
            <button class="btn-buy-item">Comprar</button>
          </div>
        </div>
      </div>

      <div class="product-comments">
        <h2>Comentarios</h2>

        <div class="product-comments-list">

          <div class="comment">

            <div class="product-seller-info">

              <div class="product-seller">
                <i class="fa-regular fa-circle-user"></i>
                <span> <%= product.user.name %> </span>
              </div>

              <div class="product-score">
                <i class="fa-solid fa-star"></i>
                <span>3.5</span>
              </div>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, disorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, distinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Verorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, distinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Vertinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Vero veniam labore non.</p>
          </div>

          <div class="comment">

            <div class="product-seller-info">

              <div class="product-seller">
                <i class="fa-regular fa-circle-user"></i>
                <span> <%= product.user.name %> </span>
              </div>

              <div class="product-score">
                <i class="fa-solid fa-star"></i>
                <span>3.5</span>
              </div>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, distinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Vero veniam labore non.</p>
          </div>

          <div class="comment">

            <div class="product-seller-info">

              <div class="product-seller">
                <i class="fa-regular fa-circle-user"></i>
                <span> <%= product.user.name %> </span>
              </div>

              <div class="product-score">
                <i class="fa-solid fa-star"></i>
                <span>3.5</span>
              </div>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, distinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Vero veniam labore non.</p>
          </div>

          <div class="comment">

            <div class="product-seller-info">

              <div class="product-seller">
                <i class="fa-regular fa-circle-user"></i>
                <span> <%= product.user.name %> </span>
              </div>

              <div class="product-score">
                <i class="fa-solid fa-star"></i>
                <span>3.5</span>
              </div>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam alias similique, distinctio quas hic placeat blanditiis soluta fugit officia beatae harum, enim sed ad voluptas exercitationem! Vero veniam labore non.</p>
          </div>
        </div>
        <div class="comment-show-more">
          <a href="/" >Mostrar más</a>
        </div>
      </div>
    </section>
  </main>
</div>

<script>
  function photos(){
    const mainImg = document.querySelector('.img-main')
    const thumbnails = document.querySelectorAll('.photo-secundary')

    thumbnails.forEach(thumb => {
      thumb.addEventListener('click', function(){
        const active = document.querySelector('.active')
        active.classList.remove('active')
        thumb.classList.add('active')
        mainImg.src = thumb.children[0].src
      })
    })
  }
  photos()
</script>

app/views/products/_product_card.html.erb
<%= link_to product do %>
  <figure>
      <%= image_tag product.photos[0].variant(resize_to_limit: [500, 700]) %>
  </figure>
<% end %>

<div class="product-card-section product-card-info">
  <%= link_to product do %>
    <h3><%= product.name %></h3>
  <% end %>

  <div>
    <i class="fa-solid fa-star"></i>
    <span>3.5</span>
  </div>
</div>

<div class="product-card-section product-price">
  <%= button_to line_items_path(:product_id => product.id) do %>
    <div>
      <i class="fa-solid fa-cart-shopping"></i>
    </div>
    <span>Agregar</span>
  <% end %>
  <span>$<%= product.price %>MXN</span>
</div>

app/views/products/edit.html.erb
<div class="form-container" data-controller="hello">
  <h1>Editar producto</h1>
  <%= render "form", product: @product %>
</div>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="product-list">
  <section class="product-filter">
    <div class="filter-list">
      <h2>Categorías</h2>
      <ul>
        <% Category.all.order(:name).map do |category| %>
          <li><%= link_to category.name, category_filter_path(category: category.name) %></li>
        <% end %>
      </ul>
    </div>
    <img src="https://jcmagazine.com/wp-content/uploads/2019/12/monitor-asus.jpg" alt="ad-1">
  </section>

  <section class="product-cards">
    <div class="product-ads">
      <img src="https://jcmagazine.com/wp-content/uploads/2019/12/monitor-asus.jpg" alt="ad-2">
      <img src="https://jcmagazine.com/wp-content/uploads/2019/12/monitor-asus.jpg" alt="ad-3">
    </div>
    <div>
      <div class="general-filter" >
        <ul id="filter-list" class="inactive">
          <li><%= link_to 'Novedades', filter_path(filter: 'date', products_id: @products.ids.to_a) %></li>
          <li><%= link_to 'Menor costo', filter_path(filter: 'price_lower', products_id: @products.ids.to_a) %></li>
          <li><%= link_to 'Mayor costo', filter_path(filter: 'price_higher', products_id: @products.ids.to_a) %></li>
        </ul>
        <i class="fa-solid fa-filter" id="filter-icon"></i>
      </div>
      <h2>Productos disponibles</h2>
      <div class="products my-products">
        <% @products.each do |product| %>
          <div class="product-card">
            <%= render 'products/product_card', product: product %>
          </div>
        <% end %>
      </div>
    </div>
    <%== pagy_nav(@pagy) %>
  </section>
</div>
<script>
  function filterInteraction() {
    const filterIcon = document.getElementById('filter-icon')
    const filterList = document.getElementById('filter-list')

    filterIcon.addEventListener('click', ()=> {
      filterList.classList.contains('inactive') ? filterList.classList.remove('inactive') : filterList.classList.add('inactive')
    })
  }

  filterInteraction();
</script>

app/views/products/my_products.html.erb
<h2>Mis productos</h2>
<div class="products my-products">
  <% @products.each do |product| %>
    <div class="product-card">
      <%= render 'product_card', product: product %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="form-container" data-controller="hello">
  <h1>Registrar producto</h1>
  <%= render "form", product: @product %>
</div>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<%= render @product %>

<% if current_user == @product.user %>
  <div class="option-links">
    <%= link_to "Editar", edit_product_path(@product) %>
    <%= link_to "Volver", products_path %>
    <%= button_to "Eliminar", @product, method: :delete, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>